# Generated by Django 5.1.4 on 2024-12-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamehistory_result_gamehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upload',
            field=models.FileField(default='', upload_to='static/'),
            preserve_default=False,
        ),
    ]
