# Generated by Django 5.1.4 on 2024-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='upload',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
